apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  namespace: ecommerce
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:

      # Frontend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80

      # Product (works directly)
      - path: /products
        pathType: Prefix
        backend:
          service:
            name: product
            port:
              number: 4001

      # Order (no middleware yet)
      - path: /order
        pathType: Prefix
        backend:
          service:
            name: order
            port:
              number: 4002

      # Payment
      - path: /payment
        pathType: Prefix
        backend:
          service:
            name: payment
            port:
              number: 4003