pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "shivanshks06/ecommerse-k8s-order-service"
    }

    stages {

        stage('Clone') {
            steps {
                git https://github.com/shivanshks06/ecommerce-k8s.git
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE:latest ./services/order'
            }
        }

        stage('Push Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhubcred',
                    usernameVariable: 'USERNAME',
                    passwordVariable: 'PASSWORD'
                )]) {
                    sh '''
                    echo $PASSWORD | docker login -u $USERNAME --password-stdin
                    docker push $DOCKER_IMAGE:latest
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/deployments/order-deployment.yaml'
            }
        }
    }
}
