pipeline {
  agent any

  environment {
    DOCKER_USER = "shivanshks06"
    VERSION = "v${BUILD_NUMBER}"
  }

  stages {

    stage('Clone') {
      steps {
        git branch: 'main', url: 'https://github.com/shivanshks06/ecommerce-k8s.git'
      }
    }

    stage('Build Images') {
      steps {
        sh '''
        docker build -t $DOCKER_USER/ecommerse-k8s-auth-service:$VERSION ./services/auth
        docker build -t $DOCKER_USER/ecommerse-k8s-product-service:$VERSION ./services/product
        docker build -t $DOCKER_USER/ecommerse-k8s-order-service:$VERSION ./services/order
        docker build -t $DOCKER_USER/ecommerse-k8s-payment-service:$VERSION ./services/payment
        docker build -t $DOCKER_USER/ecommerse-k8s-frontend:$VERSION ./services/frontend

        docker tag $DOCKER_USER/ecommerse-k8s-auth-service:$VERSION $DOCKER_USER/ecommerse-k8s-auth-service:latest
        docker tag $DOCKER_USER/ecommerse-k8s-product-service:$VERSION $DOCKER_USER/ecommerse-k8s-product-service:latest
        docker tag $DOCKER_USER/ecommerse-k8s-order-service:$VERSION $DOCKER_USER/ecommerse-k8s-order-service:latest
        docker tag $DOCKER_USER/ecommerse-k8s-payment-service:$VERSION $DOCKER_USER/ecommerse-k8s-payment-service:latest
        docker tag $DOCKER_USER/ecommerse-k8s-frontend:$VERSION $DOCKER_USER/ecommerse-k8s-frontend:latest
        '''
      }
    }

    stage('Push Images') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'dockerhubcred',
          usernameVariable: 'USER',
          passwordVariable: 'PASS'
        )]) {
          sh '''
          echo $PASS | docker login -u $USER --password-stdin

          docker push $DOCKER_USER/ecommerse-k8s-auth-service:$VERSION
          docker push $DOCKER_USER/ecommerse-k8s-product-service:$VERSION
          docker push $DOCKER_USER/ecommerse-k8s-order-service:$VERSION
          docker push $DOCKER_USER/ecommerse-k8s-payment-service:$VERSION
          docker push $DOCKER_USER/ecommerse-k8s-frontend:$VERSION

          docker push $DOCKER_USER/ecommerse-k8s-auth-service:latest
          docker push $DOCKER_USER/ecommerse-k8s-product-service:latest
          docker push $DOCKER_USER/ecommerse-k8s-order-service:latest
          docker push $DOCKER_USER/ecommerse-k8s-payment-service:latest
          docker push $DOCKER_USER/ecommerse-k8s-frontend:latest
          '''
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        sh '''
        kubectl apply -f k8s/namespace.yml

        kubectl apply -f k8s/deployments/
        kubectl apply -f k8s/services/
        kubectl apply -f k8s/ingress/
        kubectl apply -f k8s/hpa/
        '''
      }
    }

    stage('Force Rollout (Update Pods)') {
      steps {
        sh '''
        kubectl rollout restart deployment -n ecommerce
        '''
      }
    }

    stage('Verify Deployment') {
      steps {
        sh '''
        echo "===== PODS ====="
        kubectl get pods -n ecommerce

        echo "===== SERVICES ====="
        kubectl get svc -n ecommerce

        echo "===== INGRESS ====="
        kubectl get ingress -n ecommerce

        echo "===== HPA ====="
        kubectl get hpa -n ecommerce
        '''
      }
    }
  }
}
