apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: shivanshks06/ecommerse-k8s-order-service:v3
        ports:
        - containerPort: 4002

        livenessProbe:
          httpGet:
            path: /health
            port: 4002
          initialDelaySeconds: 5
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 4002
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"    
