apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: shivanshks06/ecommerse-k8s-product-service:latest
        ports:
        - containerPort: 4001

        livenessProbe:
          httpGet:
            path: /health
            port: 4001
          initialDelaySeconds: 5
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 4001
          initialDelaySeconds: 5
          periodSeconds: 10
